"""Render interface *structure* previews from the running apps into SVG.

These are not screenshots. Each preview is produced by executing the real Streamlit app with
Streamlit's own ``AppTest`` harness (or by inspecting the Gradio Blocks graph) and writing out the
labels, values and messages the app actually produces. Styling is a plain approximation; run
``scripts/capture_screenshots.py`` with a browser installed for pixel-accurate images.

Usage:  python scripts/make_previews.py     # writes docs/previews/*.svg and site/previews/*.svg
"""
from __future__ import annotations

import html
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

PROJECTS = ROOT / "projects"
STREAMLIT_APPS = [
    ("production-rag-application", "01 · Production RAG Application"),
    ("local-slm-ollama", "02 · Local SLM with Ollama"),
    ("monitoring-observability", "03 · Monitoring & Observability"),
    ("lora-dpo-fine-tuning", "04 · Fine-Tuning with LoRA & DPO"),
]
GRADIO_APP = ("realtime-multimodal", "05 · Real-Time Multimodal Application")

WIDTH, PAD, LINE = 1040, 34, 26
DISCLAIMER = "STRUCTURE PREVIEW — rendered from the running app, not a pixel screenshot"


def text_lines(text: str, width: int = 104) -> list[str]:
    words, lines, current = str(text).split(), [], ""
    for word in words:
        if len(current) + len(word) + 1 > width:
            lines.append(current)
            current = word
        else:
            current = f"{current} {word}".strip()
    if current:
        lines.append(current)
    return lines or [""]


class Svg:
    def __init__(self, title: str):
        self.title = title
        self.rows: list[tuple[str, str, str]] = []  # (kind, label, value)

    def add(self, kind: str, label: str, value: str = ""):
        self.rows.append((kind, label, value))

    def render(self) -> str:
        body, y = [], 118
        for kind, label, value in self.rows:
            if kind == "section":
                body.append(f'<text x="{PAD}" y="{y}" class="section">{html.escape(label)}</text>')
                y += LINE + 6
                continue
            colour = {"label": "#79dfbc", "note": "#f0c674", "value": "#c9d6e4",
                      "error": "#ff9c8a"}.get(kind, "#c9d6e4")
            css = {"label": "label", "note": "note", "error": "note"}.get(kind, "value")
            for index, line in enumerate(text_lines(label)):
                prefix = "▸ " if index == 0 and css != "value" else ("   " if css != "value" else "  ")
                body.append(f'<text x="{PAD}" y="{y}" class="{css}" fill="{colour}">'
                            f'{html.escape(prefix + line)}</text>')
                y += LINE
            if value:
                for index, line in enumerate(text_lines(value, 96)):
                    body.append(f'<text x="{PAD + 22}" y="{y}" class="mono">'
                                f'{html.escape(line)}</text>')
                    y += LINE
            y += 4
        height = y + 46
        return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {height}" width="{WIDTH}" height="{height}" role="img" aria-label="{html.escape(self.title)} interface structure preview">
<style>
  .title{{font:700 21px Inter,system-ui,sans-serif;fill:#edf3f7}}
  .disclaimer{{font:600 10px Inter,system-ui,sans-serif;fill:#f0c674;letter-spacing:1.4px}}
  .section{{font:700 13px Inter,system-ui,sans-serif;fill:#edf3f7;letter-spacing:.6px}}
  .label{{font:600 13px Inter,system-ui,sans-serif}}
  .value{{font:400 13px Inter,system-ui,sans-serif;fill:#c9d6e4}}
  .mono{{font:400 12px ui-monospace,SFMono-Regular,Menlo,monospace;fill:#9fb2c6}}
  .note{{font:600 12px Inter,system-ui,sans-serif}}
</style>
<rect width="{WIDTH}" height="{height}" rx="14" fill="#0b1018"/>
<rect x="0.5" y="0.5" width="{WIDTH - 1}" height="{height - 1}" rx="14" fill="none" stroke="#293648"/>
<rect x="0" y="0" width="{WIDTH}" height="8" rx="4" fill="#79dfbc"/>
<text x="{PAD}" y="56" class="title">{html.escape(self.title)}</text>
<text x="{PAD}" y="80" class="disclaimer">{DISCLAIMER}</text>
<text x="{PAD}" y="100" class="mono">generated by scripts/make_previews.py · no measurement values are claimed here</text>
{chr(10).join(body)}
</svg>
'''


def collect_streamlit(folder: str, title: str) -> Svg:
    from streamlit.testing.v1 import AppTest

    app = AppTest.from_file(str(PROJECTS / folder / "app.py")).run(timeout=30)
    svg = Svg(title)
    svg.add("section", "Page")
    for element in app.title:
        svg.add("label", f"Title: {element.value}")
    for element in app.caption:
        svg.add("value", element.value)
    svg.add("section", "Controls")
    for element in app.selectbox:
        svg.add("label", f"Selectbox · {element.label}", f"options: {', '.join(element.options)}")
    for element in app.text_area:
        svg.add("label", f"Text area · {element.label}", f"default: {element.value!r}")
    for element in app.button:
        svg.add("label", f"Button · {element.label}")
    svg.add("section", "Messages shown in this state")
    for element in app.warning:
        svg.add("note", element.value)
    for element in app.info:
        svg.add("value", element.value)
    for element in app.success:
        svg.add("value", element.value)
    for element in app.error:
        svg.add("error", element.value)
    for element in app.markdown:
        if len(element.value) < 220:
            svg.add("value", element.value.replace("**", ""))
    return svg


def collect_gradio() -> Svg:
    import importlib.util

    spec = importlib.util.spec_from_file_location("preview_voice", PROJECTS / GRADIO_APP[0] / "app.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    demo = module.build_app()
    svg = Svg(GRADIO_APP[1])
    svg.add("section", "Page")
    for block in demo.blocks.values():
        value = getattr(block, "value", None)
        if block.__class__.__name__ == "Markdown" and isinstance(value, str):
            for line in value.replace("#", "").split("\n"):
                if line.strip():
                    svg.add("label" if line.startswith(" ") else "value", line.strip())
    svg.add("section", "Controls")
    for block in demo.blocks.values():
        if block.__class__.__name__ in {"Textbox", "Audio", "Checkbox", "Button"}:
            svg.add("label", f"{block.__class__.__name__} · {getattr(block, 'label', '')}")
    svg.add("note", "Local STT state is printed at runtime from ENABLE_LOCAL_STT "
                    "(the Docker image sets it to 1).")
    return svg


def main() -> None:
    targets = [ROOT / "docs" / "previews", ROOT / "site" / "previews"]
    for target in targets:
        target.mkdir(parents=True, exist_ok=True)
    for folder, title in STREAMLIT_APPS:
        svg = collect_streamlit(folder, title)
        for target in targets:
            (target / f"{folder}.svg").write_text(svg.render())
        print("wrote", folder)
    svg = collect_gradio()
    for target in targets:
        (target / f"{GRADIO_APP[0]}.svg").write_text(svg.render())
    print("wrote", GRADIO_APP[0])


if __name__ == "__main__":
    main()
    shutil.rmtree(ROOT / ".streamlit_preview_cache", ignore_errors=True)
